### ISSUE TITLE
gRainbow1.0.3_Linux .vst3 cant load in Reaper 7.11_x64

### ISSUE THREAD

**Issue by ghost** [bboettcher3/gRainbow#93] opened 2024-02-29 19:39 UTC
gRainbow.1.0.3 .vst3 that i had fails to load into Reaper 7.11_x64.

 - OS: Linux Mint 21.3 Cinnamom_x64
 - gRainbow version 1.0.3

Thanks for this software!

https://imgur.com/AeYGVqM

**Comment by andrewhendri** [comment] 2024-03-01 00:40
same here on Mint 21.2 XFCE

**Comment by sjfricke** [comment] 2024-03-01 00:43
sorry, this is another duplicate of https://github.com/StrangeLoopsAudio/gRainbow/issues/85#issuecomment-1925204730

tl;dr I added a `gRainbow-1.0.3-Linux-patch.tar.gz` to https://github.com/StrangeLoopsAudio/gRainbow/releases/tag/v1.0.3

This weekend I plan to finally fix the issue and update all the spots

**Comment by ghost** [comment] 2024-03-08 12:59
thank you!!!
I will try it as soon as possible. Great job
:-)

**Closed as completed** 2024-10-30 01:56 UTC
Labels: bug
